# Generated by Django 4.1 on 2022-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotels_airplane_prices_hotels_best_hotels_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=255, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={},
        ),
    ]
