# Generated by Django 4.1 on 2022-11-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_delete_currency_hotels_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
