# Generated by Django 4.1 on 2022-11-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюты', 'verbose_name_plural': 'Валюты'},
        ),
    ]
