# Generated by Django 4.1 on 2022-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status_contact',
            field=models.BooleanField(default=False, verbose_name='Статус контакта'),
        ),
    ]
