# Generated by Django 4.1 on 2022-11-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_currency_options'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights_currency', to='settings.currency', verbose_name='Название валюты'),
            preserve_default=False,
        ),
    ]
